"""
Prompts Library for EnsureU AI
"""
from .exam_prompts import (
    # Question Generation
    QUESTION_GENERATION_SYSTEM,
    QUESTION_GENERATION_PROMPT,
    BULK_QUESTION_GENERATION_PROMPT,
    # Wrong Answer Explanation
    WRONG_ANSWER_EXPLANATION_SYSTEM,
    WRONG_ANSWER_EXPLANATION_PROMPT,
    # Performance Analysis
    EXAM_ANALYSIS_SYSTEM,
    EXAM_ANALYSIS_PROMPT,
    # Study Plan
    STUDY_PLAN_SYSTEM,
    STUDY_PLAN_PROMPT,
    # Adaptive Selection
    QUESTION_SELECTION_PROMPT,
    # Diagnostic
    DIAGNOSTIC_ANALYSIS_PROMPT,
    # Hints
    HINT_GENERATION_PROMPT,
    # Paper Quality
    PAPER_QUALITY_ANALYSIS_PROMPT,
    # Guardrails
    EXAM_GUARDRAILS_SYSTEM,
)

__all__ = [
    "QUESTION_GENERATION_SYSTEM",
    "QUESTION_GENERATION_PROMPT",
    "BULK_QUESTION_GENERATION_PROMPT",
    "WRONG_ANSWER_EXPLANATION_SYSTEM",
    "WRONG_ANSWER_EXPLANATION_PROMPT",
    "EXAM_ANALYSIS_SYSTEM",
    "EXAM_ANALYSIS_PROMPT",
    "STUDY_PLAN_SYSTEM",
    "STUDY_PLAN_PROMPT",
    "QUESTION_SELECTION_PROMPT",
    "DIAGNOSTIC_ANALYSIS_PROMPT",
    "HINT_GENERATION_PROMPT",
    "PAPER_QUALITY_ANALYSIS_PROMPT",
    "EXAM_GUARDRAILS_SYSTEM",
]
